{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "MjU5EYkgevA3"
      },
      "source": [
        "Logging is way to track events , errors and operational information.\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 3,
      "metadata": {
        "id": "FsZHsryGedkK"
      },
      "outputs": [],
      "source": [
        "import logging"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 4,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "CG9zumdke-K4",
        "outputId": "f6a78ab9-8264-41f8-bb16-8de3dae01bc8"
      },
      "outputs": [
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "--- Logging error ---\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 1083, in emit\n",
            "    msg = self.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 927, in format\n",
            "    return fmt.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 666, in format\n",
            "    s = self.formatMessage(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 635, in formatMessage\n",
            "    return self._style.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 434, in format\n",
            "    return self._format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 430, in _format\n",
            "    return self._fmt % record.__dict__\n",
            "ValueError: unsupported format character '%' (0x25) at index 20\n",
            "Call stack:\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 87, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
            "    app.launch_new_instance()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\traitlets\\config\\application.py\", line 845, in launch_instance\n",
            "    app.start()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 612, in start\n",
            "    self.io_loop.start()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
            "    self.asyncio_loop.run_forever()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\windows_events.py\", line 316, in run_forever\n",
            "    super().run_forever()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 596, in run_forever\n",
            "    self._run_once()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 1890, in _run_once\n",
            "    handle._run()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\events.py\", line 80, in _run\n",
            "    self._context.run(self._callback, *self._args)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\ioloop.py\", line 688, in <lambda>\n",
            "    lambda f: self._run_callback(functools.partial(callback, future))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\ioloop.py\", line 741, in _run_callback\n",
            "    ret = callback()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 814, in inner\n",
            "    self.ctx_run(self.run)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 775, in run\n",
            "    yielded = self.gen.send(value)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 358, in process_one\n",
            "    yield gen.maybe_future(dispatch(*args))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 261, in dispatch_shell\n",
            "    yield gen.maybe_future(handler(stream, idents, msg))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 536, in execute_request\n",
            "    self.do_execute(\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 302, in do_execute\n",
            "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 539, in run_cell\n",
            "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2894, in run_cell\n",
            "    result = self._run_cell(\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2940, in _run_cell\n",
            "    return runner(coro)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
            "    coro.send(None)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3165, in run_cell_async\n",
            "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3357, in run_ast_nodes\n",
            "    if (await self.run_code(code, result,  async_=asy)):\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3437, in run_code\n",
            "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
            "  File \"<ipython-input-4-49358966a32d>\", line 5, in <module>\n",
            "    logging.debug('This is a debug message')\n",
            "Message: 'This is a debug message'\n",
            "Arguments: ()\n",
            "--- Logging error ---\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 1083, in emit\n",
            "    msg = self.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 927, in format\n",
            "    return fmt.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 666, in format\n",
            "    s = self.formatMessage(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 635, in formatMessage\n",
            "    return self._style.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 434, in format\n",
            "    return self._format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 430, in _format\n",
            "    return self._fmt % record.__dict__\n",
            "ValueError: unsupported format character '%' (0x25) at index 20\n",
            "Call stack:\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 87, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
            "    app.launch_new_instance()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\traitlets\\config\\application.py\", line 845, in launch_instance\n",
            "    app.start()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 612, in start\n",
            "    self.io_loop.start()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
            "    self.asyncio_loop.run_forever()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\windows_events.py\", line 316, in run_forever\n",
            "    super().run_forever()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 596, in run_forever\n",
            "    self._run_once()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 1890, in _run_once\n",
            "    handle._run()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\events.py\", line 80, in _run\n",
            "    self._context.run(self._callback, *self._args)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\ioloop.py\", line 688, in <lambda>\n",
            "    lambda f: self._run_callback(functools.partial(callback, future))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\ioloop.py\", line 741, in _run_callback\n",
            "    ret = callback()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 814, in inner\n",
            "    self.ctx_run(self.run)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 775, in run\n",
            "    yielded = self.gen.send(value)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 358, in process_one\n",
            "    yield gen.maybe_future(dispatch(*args))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 261, in dispatch_shell\n",
            "    yield gen.maybe_future(handler(stream, idents, msg))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 536, in execute_request\n",
            "    self.do_execute(\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 302, in do_execute\n",
            "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 539, in run_cell\n",
            "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2894, in run_cell\n",
            "    result = self._run_cell(\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2940, in _run_cell\n",
            "    return runner(coro)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
            "    coro.send(None)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3165, in run_cell_async\n",
            "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3357, in run_ast_nodes\n",
            "    if (await self.run_code(code, result,  async_=asy)):\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3437, in run_code\n",
            "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
            "  File \"<ipython-input-4-49358966a32d>\", line 6, in <module>\n",
            "    logging.info('This is an info message')\n",
            "Message: 'This is an info message'\n",
            "Arguments: ()\n",
            "--- Logging error ---\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 1083, in emit\n",
            "    msg = self.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 927, in format\n",
            "    return fmt.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 666, in format\n",
            "    s = self.formatMessage(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 635, in formatMessage\n",
            "    return self._style.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 434, in format\n",
            "    return self._format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 430, in _format\n",
            "    return self._fmt % record.__dict__\n",
            "ValueError: unsupported format character '%' (0x25) at index 20\n",
            "Call stack:\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 87, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
            "    app.launch_new_instance()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\traitlets\\config\\application.py\", line 845, in launch_instance\n",
            "    app.start()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 612, in start\n",
            "    self.io_loop.start()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
            "    self.asyncio_loop.run_forever()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\windows_events.py\", line 316, in run_forever\n",
            "    super().run_forever()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 596, in run_forever\n",
            "    self._run_once()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 1890, in _run_once\n",
            "    handle._run()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\events.py\", line 80, in _run\n",
            "    self._context.run(self._callback, *self._args)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\ioloop.py\", line 688, in <lambda>\n",
            "    lambda f: self._run_callback(functools.partial(callback, future))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\ioloop.py\", line 741, in _run_callback\n",
            "    ret = callback()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 814, in inner\n",
            "    self.ctx_run(self.run)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 775, in run\n",
            "    yielded = self.gen.send(value)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 358, in process_one\n",
            "    yield gen.maybe_future(dispatch(*args))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 261, in dispatch_shell\n",
            "    yield gen.maybe_future(handler(stream, idents, msg))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 536, in execute_request\n",
            "    self.do_execute(\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 302, in do_execute\n",
            "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 539, in run_cell\n",
            "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2894, in run_cell\n",
            "    result = self._run_cell(\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2940, in _run_cell\n",
            "    return runner(coro)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
            "    coro.send(None)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3165, in run_cell_async\n",
            "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3357, in run_ast_nodes\n",
            "    if (await self.run_code(code, result,  async_=asy)):\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3437, in run_code\n",
            "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
            "  File \"<ipython-input-4-49358966a32d>\", line 7, in <module>\n",
            "    logging.warning('This is a warning message')\n",
            "Message: 'This is a warning message'\n",
            "Arguments: ()\n",
            "--- Logging error ---\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 1083, in emit\n",
            "    msg = self.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 927, in format\n",
            "    return fmt.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 666, in format\n",
            "    s = self.formatMessage(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 635, in formatMessage\n",
            "    return self._style.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 434, in format\n",
            "    return self._format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 430, in _format\n",
            "    return self._fmt % record.__dict__\n",
            "ValueError: unsupported format character '%' (0x25) at index 20\n",
            "Call stack:\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 87, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
            "    app.launch_new_instance()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\traitlets\\config\\application.py\", line 845, in launch_instance\n",
            "    app.start()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 612, in start\n",
            "    self.io_loop.start()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
            "    self.asyncio_loop.run_forever()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\windows_events.py\", line 316, in run_forever\n",
            "    super().run_forever()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 596, in run_forever\n",
            "    self._run_once()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 1890, in _run_once\n",
            "    handle._run()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\events.py\", line 80, in _run\n",
            "    self._context.run(self._callback, *self._args)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\ioloop.py\", line 688, in <lambda>\n",
            "    lambda f: self._run_callback(functools.partial(callback, future))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\ioloop.py\", line 741, in _run_callback\n",
            "    ret = callback()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 814, in inner\n",
            "    self.ctx_run(self.run)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 775, in run\n",
            "    yielded = self.gen.send(value)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 358, in process_one\n",
            "    yield gen.maybe_future(dispatch(*args))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 261, in dispatch_shell\n",
            "    yield gen.maybe_future(handler(stream, idents, msg))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 536, in execute_request\n",
            "    self.do_execute(\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 302, in do_execute\n",
            "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 539, in run_cell\n",
            "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2894, in run_cell\n",
            "    result = self._run_cell(\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2940, in _run_cell\n",
            "    return runner(coro)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
            "    coro.send(None)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3165, in run_cell_async\n",
            "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3357, in run_ast_nodes\n",
            "    if (await self.run_code(code, result,  async_=asy)):\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3437, in run_code\n",
            "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
            "  File \"<ipython-input-4-49358966a32d>\", line 8, in <module>\n",
            "    logging.error('This is an error message')\n",
            "Message: 'This is an error message'\n",
            "Arguments: ()\n",
            "--- Logging error ---\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 1083, in emit\n",
            "    msg = self.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 927, in format\n",
            "    return fmt.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 666, in format\n",
            "    s = self.formatMessage(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 635, in formatMessage\n",
            "    return self._style.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 434, in format\n",
            "    return self._format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 430, in _format\n",
            "    return self._fmt % record.__dict__\n",
            "ValueError: unsupported format character '%' (0x25) at index 20\n",
            "Call stack:\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 87, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
            "    app.launch_new_instance()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\traitlets\\config\\application.py\", line 845, in launch_instance\n",
            "    app.start()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 612, in start\n",
            "    self.io_loop.start()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
            "    self.asyncio_loop.run_forever()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\windows_events.py\", line 316, in run_forever\n",
            "    super().run_forever()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 596, in run_forever\n",
            "    self._run_once()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 1890, in _run_once\n",
            "    handle._run()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\events.py\", line 80, in _run\n",
            "    self._context.run(self._callback, *self._args)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\ioloop.py\", line 688, in <lambda>\n",
            "    lambda f: self._run_callback(functools.partial(callback, future))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\ioloop.py\", line 741, in _run_callback\n",
            "    ret = callback()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 814, in inner\n",
            "    self.ctx_run(self.run)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 775, in run\n",
            "    yielded = self.gen.send(value)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 358, in process_one\n",
            "    yield gen.maybe_future(dispatch(*args))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 261, in dispatch_shell\n",
            "    yield gen.maybe_future(handler(stream, idents, msg))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 536, in execute_request\n",
            "    self.do_execute(\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 302, in do_execute\n",
            "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 539, in run_cell\n",
            "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2894, in run_cell\n",
            "    result = self._run_cell(\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2940, in _run_cell\n",
            "    return runner(coro)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
            "    coro.send(None)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3165, in run_cell_async\n",
            "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3357, in run_ast_nodes\n",
            "    if (await self.run_code(code, result,  async_=asy)):\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3437, in run_code\n",
            "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
            "  File \"<ipython-input-4-49358966a32d>\", line 9, in <module>\n",
            "    logging.critical('This is a critical message')\n",
            "Message: 'This is a critical message'\n",
            "Arguments: ()\n"
          ]
        }
      ],
      "source": [
        "# OCnfigurations for logging\n",
        "logging.basicConfig(level = logging.DEBUG)\n",
        "\n",
        "# log messages\n",
        "logging.debug('This is a debug message')\n",
        "logging.info('This is an info message')\n",
        "logging.warning('This is a warning message')\n",
        "logging.error('This is an error message')\n",
        "logging.critical('This is a critical message')"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "YFlfG-iWfpDF"
      },
      "source": [
        "Log Levels\n",
        "Python's logging module has several log levels indicating the severity of events. The default levels are:\n",
        "\n",
        "DEBUG: Detailed information, typically of interest only when diagnosing problems.\n",
        "INFO: Confirmation that things are working as expected.\n",
        "WARNING: An indication that something unexpected happened or indicative of some problem in the near future (e.g., ‘disk space low’). The software is still working as expected.\n",
        "ERROR: Due to a more serious problem, the software has not been able to perform some function.\n",
        "CRITICAL: A very serious error, indicating that the program itself may be unable to continue running."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 5,
      "metadata": {
        "id": "bNb2QY53fV4R"
      },
      "outputs": [],
      "source": [
        "## configuring the logging\n",
        "logging.basicConfig(\n",
        "    level=logging.DEBUG,\n",
        "    format = '%(asctime)s-%(name)-%(levelname)s-%(message)s',\n",
        "    datefmt = '%Y-%m-%d %H:%M:%S'\n",
        ")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 6,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "3Z5Ls6Dqgcdz",
        "outputId": "95d17d46-6c91-4582-d75c-9363c4230007"
      },
      "outputs": [
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "--- Logging error ---\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 1083, in emit\n",
            "    msg = self.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 927, in format\n",
            "    return fmt.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 666, in format\n",
            "    s = self.formatMessage(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 635, in formatMessage\n",
            "    return self._style.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 434, in format\n",
            "    return self._format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 430, in _format\n",
            "    return self._fmt % record.__dict__\n",
            "ValueError: unsupported format character '%' (0x25) at index 20\n",
            "Call stack:\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 87, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
            "    app.launch_new_instance()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\traitlets\\config\\application.py\", line 845, in launch_instance\n",
            "    app.start()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 612, in start\n",
            "    self.io_loop.start()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
            "    self.asyncio_loop.run_forever()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\windows_events.py\", line 316, in run_forever\n",
            "    super().run_forever()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 596, in run_forever\n",
            "    self._run_once()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 1890, in _run_once\n",
            "    handle._run()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\events.py\", line 80, in _run\n",
            "    self._context.run(self._callback, *self._args)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\ioloop.py\", line 688, in <lambda>\n",
            "    lambda f: self._run_callback(functools.partial(callback, future))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\ioloop.py\", line 741, in _run_callback\n",
            "    ret = callback()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 814, in inner\n",
            "    self.ctx_run(self.run)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 775, in run\n",
            "    yielded = self.gen.send(value)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 358, in process_one\n",
            "    yield gen.maybe_future(dispatch(*args))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 261, in dispatch_shell\n",
            "    yield gen.maybe_future(handler(stream, idents, msg))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 536, in execute_request\n",
            "    self.do_execute(\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 302, in do_execute\n",
            "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 539, in run_cell\n",
            "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2894, in run_cell\n",
            "    result = self._run_cell(\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2940, in _run_cell\n",
            "    return runner(coro)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
            "    coro.send(None)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3165, in run_cell_async\n",
            "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3357, in run_ast_nodes\n",
            "    if (await self.run_code(code, result,  async_=asy)):\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3437, in run_code\n",
            "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
            "  File \"<ipython-input-6-dcf62c21a545>\", line 11, in <module>\n",
            "    logging.debug('This is a debug message')\n",
            "Message: 'This is a debug message'\n",
            "Arguments: ()\n",
            "--- Logging error ---\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 1083, in emit\n",
            "    msg = self.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 927, in format\n",
            "    return fmt.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 666, in format\n",
            "    s = self.formatMessage(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 635, in formatMessage\n",
            "    return self._style.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 434, in format\n",
            "    return self._format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 430, in _format\n",
            "    return self._fmt % record.__dict__\n",
            "ValueError: unsupported format character '%' (0x25) at index 20\n",
            "Call stack:\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 87, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
            "    app.launch_new_instance()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\traitlets\\config\\application.py\", line 845, in launch_instance\n",
            "    app.start()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 612, in start\n",
            "    self.io_loop.start()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
            "    self.asyncio_loop.run_forever()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\windows_events.py\", line 316, in run_forever\n",
            "    super().run_forever()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 596, in run_forever\n",
            "    self._run_once()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 1890, in _run_once\n",
            "    handle._run()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\events.py\", line 80, in _run\n",
            "    self._context.run(self._callback, *self._args)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\ioloop.py\", line 688, in <lambda>\n",
            "    lambda f: self._run_callback(functools.partial(callback, future))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\ioloop.py\", line 741, in _run_callback\n",
            "    ret = callback()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 814, in inner\n",
            "    self.ctx_run(self.run)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 775, in run\n",
            "    yielded = self.gen.send(value)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 358, in process_one\n",
            "    yield gen.maybe_future(dispatch(*args))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 261, in dispatch_shell\n",
            "    yield gen.maybe_future(handler(stream, idents, msg))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 536, in execute_request\n",
            "    self.do_execute(\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 302, in do_execute\n",
            "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 539, in run_cell\n",
            "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2894, in run_cell\n",
            "    result = self._run_cell(\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2940, in _run_cell\n",
            "    return runner(coro)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
            "    coro.send(None)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3165, in run_cell_async\n",
            "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3357, in run_ast_nodes\n",
            "    if (await self.run_code(code, result,  async_=asy)):\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3437, in run_code\n",
            "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
            "  File \"<ipython-input-6-dcf62c21a545>\", line 12, in <module>\n",
            "    logging.info('This is an info message')\n",
            "Message: 'This is an info message'\n",
            "Arguments: ()\n",
            "--- Logging error ---\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 1083, in emit\n",
            "    msg = self.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 927, in format\n",
            "    return fmt.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 666, in format\n",
            "    s = self.formatMessage(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 635, in formatMessage\n",
            "    return self._style.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 434, in format\n",
            "    return self._format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 430, in _format\n",
            "    return self._fmt % record.__dict__\n",
            "ValueError: unsupported format character '%' (0x25) at index 20\n",
            "Call stack:\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 87, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
            "    app.launch_new_instance()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\traitlets\\config\\application.py\", line 845, in launch_instance\n",
            "    app.start()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 612, in start\n",
            "    self.io_loop.start()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
            "    self.asyncio_loop.run_forever()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\windows_events.py\", line 316, in run_forever\n",
            "    super().run_forever()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 596, in run_forever\n",
            "    self._run_once()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 1890, in _run_once\n",
            "    handle._run()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\events.py\", line 80, in _run\n",
            "    self._context.run(self._callback, *self._args)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\ioloop.py\", line 688, in <lambda>\n",
            "    lambda f: self._run_callback(functools.partial(callback, future))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\ioloop.py\", line 741, in _run_callback\n",
            "    ret = callback()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 814, in inner\n",
            "    self.ctx_run(self.run)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 775, in run\n",
            "    yielded = self.gen.send(value)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 358, in process_one\n",
            "    yield gen.maybe_future(dispatch(*args))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 261, in dispatch_shell\n",
            "    yield gen.maybe_future(handler(stream, idents, msg))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 536, in execute_request\n",
            "    self.do_execute(\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 302, in do_execute\n",
            "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 539, in run_cell\n",
            "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2894, in run_cell\n",
            "    result = self._run_cell(\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2940, in _run_cell\n",
            "    return runner(coro)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
            "    coro.send(None)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3165, in run_cell_async\n",
            "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3357, in run_ast_nodes\n",
            "    if (await self.run_code(code, result,  async_=asy)):\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3437, in run_code\n",
            "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
            "  File \"<ipython-input-6-dcf62c21a545>\", line 13, in <module>\n",
            "    logging.warning('This is a warning message')\n",
            "Message: 'This is a warning message'\n",
            "Arguments: ()\n",
            "--- Logging error ---\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 1083, in emit\n",
            "    msg = self.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 927, in format\n",
            "    return fmt.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 666, in format\n",
            "    s = self.formatMessage(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 635, in formatMessage\n",
            "    return self._style.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 434, in format\n",
            "    return self._format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 430, in _format\n",
            "    return self._fmt % record.__dict__\n",
            "ValueError: unsupported format character '%' (0x25) at index 20\n",
            "Call stack:\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 87, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
            "    app.launch_new_instance()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\traitlets\\config\\application.py\", line 845, in launch_instance\n",
            "    app.start()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 612, in start\n",
            "    self.io_loop.start()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
            "    self.asyncio_loop.run_forever()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\windows_events.py\", line 316, in run_forever\n",
            "    super().run_forever()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 596, in run_forever\n",
            "    self._run_once()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 1890, in _run_once\n",
            "    handle._run()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\events.py\", line 80, in _run\n",
            "    self._context.run(self._callback, *self._args)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\ioloop.py\", line 688, in <lambda>\n",
            "    lambda f: self._run_callback(functools.partial(callback, future))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\ioloop.py\", line 741, in _run_callback\n",
            "    ret = callback()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 814, in inner\n",
            "    self.ctx_run(self.run)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 775, in run\n",
            "    yielded = self.gen.send(value)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 358, in process_one\n",
            "    yield gen.maybe_future(dispatch(*args))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 261, in dispatch_shell\n",
            "    yield gen.maybe_future(handler(stream, idents, msg))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 536, in execute_request\n",
            "    self.do_execute(\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 302, in do_execute\n",
            "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 539, in run_cell\n",
            "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2894, in run_cell\n",
            "    result = self._run_cell(\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2940, in _run_cell\n",
            "    return runner(coro)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
            "    coro.send(None)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3165, in run_cell_async\n",
            "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3357, in run_ast_nodes\n",
            "    if (await self.run_code(code, result,  async_=asy)):\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3437, in run_code\n",
            "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
            "  File \"<ipython-input-6-dcf62c21a545>\", line 14, in <module>\n",
            "    logging.error('This is an error message')\n",
            "Message: 'This is an error message'\n",
            "Arguments: ()\n",
            "--- Logging error ---\n",
            "Traceback (most recent call last):\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 1083, in emit\n",
            "    msg = self.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 927, in format\n",
            "    return fmt.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 666, in format\n",
            "    s = self.formatMessage(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 635, in formatMessage\n",
            "    return self._style.format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 434, in format\n",
            "    return self._format(record)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\logging\\__init__.py\", line 430, in _format\n",
            "    return self._fmt % record.__dict__\n",
            "ValueError: unsupported format character '%' (0x25) at index 20\n",
            "Call stack:\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 197, in _run_module_as_main\n",
            "    return _run_code(code, main_globals, None,\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\runpy.py\", line 87, in _run_code\n",
            "    exec(code, run_globals)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
            "    app.launch_new_instance()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\traitlets\\config\\application.py\", line 845, in launch_instance\n",
            "    app.start()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 612, in start\n",
            "    self.io_loop.start()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n",
            "    self.asyncio_loop.run_forever()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\windows_events.py\", line 316, in run_forever\n",
            "    super().run_forever()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 596, in run_forever\n",
            "    self._run_once()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\base_events.py\", line 1890, in _run_once\n",
            "    handle._run()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\asyncio\\events.py\", line 80, in _run\n",
            "    self._context.run(self._callback, *self._args)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\ioloop.py\", line 688, in <lambda>\n",
            "    lambda f: self._run_callback(functools.partial(callback, future))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\ioloop.py\", line 741, in _run_callback\n",
            "    ret = callback()\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 814, in inner\n",
            "    self.ctx_run(self.run)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 775, in run\n",
            "    yielded = self.gen.send(value)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 358, in process_one\n",
            "    yield gen.maybe_future(dispatch(*args))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 261, in dispatch_shell\n",
            "    yield gen.maybe_future(handler(stream, idents, msg))\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 536, in execute_request\n",
            "    self.do_execute(\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\tornado\\gen.py\", line 234, in wrapper\n",
            "    yielded = ctx_run(next, result)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 302, in do_execute\n",
            "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 539, in run_cell\n",
            "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2894, in run_cell\n",
            "    result = self._run_cell(\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2940, in _run_cell\n",
            "    return runner(coro)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
            "    coro.send(None)\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3165, in run_cell_async\n",
            "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3357, in run_ast_nodes\n",
            "    if (await self.run_code(code, result,  async_=asy)):\n",
            "  File \"c:\\Users\\aanan\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3437, in run_code\n",
            "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
            "  File \"<ipython-input-6-dcf62c21a545>\", line 15, in <module>\n",
            "    logging.critical('This is a critical message')\n",
            "Message: 'This is a critical message'\n",
            "Arguments: ()\n"
          ]
        }
      ],
      "source": [
        "## configuring the logging\n",
        "logging.basicConfig(\n",
        "    filename='app.log',\n",
        "    filemode='w',\n",
        "    level=logging.DEBUG,\n",
        "    format = '%(asctime)s-%(name)-%(levelname)s-%(message)s',\n",
        "    datefmt = '%Y-%m-%d %H:%M:%S'\n",
        ")\n",
        "\n",
        "# log messages\n",
        "logging.debug('This is a debug message')\n",
        "logging.info('This is an info message')\n",
        "logging.warning('This is a warning message')\n",
        "logging.error('This is an error message')\n",
        "logging.critical('This is a critical message')"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "lFchaRnvg4s8"
      },
      "outputs": [],
      "source": []
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": []
    }
  ],
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.9.4"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
